{% set name = "gcn-kafka" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44747bdb0e25362887d9e421f63480c6701a9b6e0a3b3019a799cd905607d308

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - setuptools >=45
    - setuptools_scm >=6.2
    - wheel
    - python >=3.7
    - pip
  run:
    - authlib
    - certifi
    - python-confluent-kafka >=1.6.1
    - requests
    - python >=3.7
    - typing_extensions

test:
  imports:
    - gcn_kafka
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tachgsfc/gcn-kafka-python
  summary: Official Python client for the General Coordinates Network (GCN)
  description: |
    This is the official Python client for the General Coordinates Network (GCN).
    It is a very lightweight wrapper around confluent-kafka-python.
  license: CC0-1.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - lpsinger
