{% set name = "gcn-kafka" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 47ed3dbc94d1d981374e7e573a05ecc17356e577409a363f32a9891b1a7ad2be

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - setuptools >=45
    - setuptools_scm >=6.2
    - wheel
    - python {{ python_min }}
    - pip
  run:
    - certifi
    - python-confluent-kafka >=2.11.0
    - python >={{ python_min }}

test:
  imports:
    - gcn_kafka
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/nasa-gcn/gcn-kafka-python
  summary: Official Python client for the General Coordinates Network (GCN)
  description: |
    This is the official Python client for the General Coordinates Network (GCN).
    It is a very lightweight wrapper around confluent-kafka-python.
  license: CC0-1.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - lpsinger
    - dakota002
